#compdef parameter-sweep.py
#
# this is zsh completion function file.
# generated by genzshcomp(ver: 0.5.1)
#

typeset -A opt_args
local context state line

_arguments -s -S \
  "-h[show this help message and exit]:" \
  "--help[show this help message and exit]:" \
  "--debug-mode[Enable debugging mode (run in serial).]" \
  "-p[Do a standard parameter sweep with the specified parameter set.]::PARAMETERS:_files" \
  "--parameters[Do a standard parameter sweep with the specified parameter set.]::PARAMETERS:_files" \
  "--clean[clean up old results from the target folder]" \
  "-j[Number of processes to run at once.]::NCORES:_files" \
  "--ncores[Number of processes to run at once.]::NCORES:_files" \
  "--no-build[Don't rebuild anything]" \
  "*::args:_files"
